#pragma once

// Tamaño del board según el nivel
#define BOARD_SIZE_PLANETS  9
#define BOARD_SIZE_PLUTO    8
#define BOARD_SIZE_SUN     10

// Numero de movimientos por nivel
#define MOVES_LEVEL_1   30  // Neptuno
#define MOVES_LEVEL_2   30  // Urano
#define MOVES_LEVEL_3   30  // Saturno
#define MOVES_LEVEL_4   30  // Jupiter
#define MOVES_LEVEL_5   30  // Marte
#define MOVES_LEVEL_6   30  // Tierra
#define MOVES_LEVEL_7   30  // Venus
#define MOVES_LEVEL_8   30  // Mercurio
#define MOVES_LEVEL_9   35  // Sol

// Puntuación a alcanzar en cada nivel
#define GOAL_SCORE_1    30
#define GOAL_SCORE_2    30
#define GOAL_SCORE_3    30
#define GOAL_SCORE_4    30
#define GOAL_SCORE_5    30
#define GOAL_SCORE_6    30
#define GOAL_SCORE_7    30
#define GOAL_SCORE_8    30
#define GOAL_SCORE_9    30

// Tiempo disponible en el nivel bonus (Plutón)
#define SECONDS_BONUS_LEVEL   60

