#pragma once

// Tamaño del board según el nivel
#define BOARD_SIZE_PLANETS  9
#define BOARD_SIZE_PLUTO    8
#define BOARD_SIZE_SUN     10

// Numero de movimientos por nivel
#define MOVES_LEVEL_1   30  // Neptuno
#define MOVES_LEVEL_2   30  // Urano
#define MOVES_LEVEL_3   30  // Saturno
#define MOVES_LEVEL_4   30  // Jupiter
#define MOVES_LEVEL_5   30  // Marte
#define MOVES_LEVEL_6   30  // Tierra
#define MOVES_LEVEL_7   30  // Venus
#define MOVES_LEVEL_8   30  // Mercurio
#define MOVES_LEVEL_9   30  // Sol
#define MOVES_LEVEL_10  30  // Plutón

// Puntuación a alcanzar en cada nivel
#define GOAL_SCORE_1    50
#define GOAL_SCORE_2    70
#define GOAL_SCORE_3    70
#define GOAL_SCORE_4    70
#define GOAL_SCORE_5    70
#define GOAL_SCORE_6    70
#define GOAL_SCORE_7    70
#define GOAL_SCORE_8    70
#define GOAL_SCORE_9    70

// Tiempo disponible en el nivel bonus (Plutón)
#define SECONDS_BONUS_LEVEL   60

